gitops-runtime:
  app-proxy:
    config:
      cors: http://local.codefresh.io,https://kim-platform.ngrok.io
      graphqlPlayground: 'true'
  argo-events:
    global:
      image:
        tag: release-1.9
  global:
    codefresh:
      url: https://kim-platform.ngrok.io
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      cluster: https://kubernetes.default.svc
      codefreshHosted: false
      ingress:
        className: nginx-internal
        enabled: true
        hosts:
          - kim-local.rnd-sandbox.cf-infra.com
        protocol: https
      name: kim-local-helm-runtime
  installer:
    skipValidation: true
